### ISSUE TITLE
Basemap is white

### ISSUE THREAD

**Issue by endolith** [coregis/alternative-voting#3]
![2020-11-18 13_31_44-Clipboard](https://user-images.githubusercontent.com/58611/99572348-83f14500-29a2-11eb-88e2-9d7537c81f63.png)

Chrome Version 86.0.4240.198

Waterfox 2020.10

IE doesn't even display the placemarks

**Comment by coregis** [comment]
Hi @endolith, as I mentioned in previous comment this project was completed in 2017 and is not being updated.
