### ISSUE TITLE
Update with Approval Voting and IRV adoptions

### ISSUE THREAD

**Issue by endolith** [coregis/alternative-voting#4]
Fargo ND adopted Approval Voting (at large) in 2018

St Louis MO adopted Approval Voting (plus runoff) in November 2020

Alaska adopted IRV in November 2020

**Comment by coregis** [comment]
Thanks for the feedback @endolith,  this project was completed in 2017 and is no longer under active development or being updated, although Sightline might revisit it given the recent election results.
